services:
  - type: web
    name: maneiro-web
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: maneiro-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: maneiro-redis
          type: redis
          property: connectionString
  - type: redis
    name: maneiro-redis
    plan: starter
  - type: pserv
    name: maneiro-db
    plan: starter
    postgresMajorVersion: 15
