services:
  - type: web
    name: ai4doctors
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: OPENAI_MODEL
        value: gpt-4.1
